version: "{build}"

branches:
  only:
    - master

build: false

environment:
  nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install -g grunt-cli

test_script:
  - grunt build-browser-compressed
